
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pizza-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./pizza.db  # Local sin Postgres
    volumes:
      - ./backend/app:/app/app:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pizza-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
